### ISSUE TITLE
ModuleNotFoundError: No module named 'OpenAIAuth.OpenAIAuth';

### ISSUE THREAD

**Issue by chz091** [AkashiCoin/nonebot-plugin-chatgpt-plus#1]
大佬求助，bot回复这个是什么原因？
我用 pip install OpenAIAuth后依旧未解决这个问题

请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: ModuleNotFoundError: No module named 'OpenAIAuth.OpenAIAuth'; 'OpenAIAuth' is not a package

**Comment by chz091** [comment]
![image](https://user-images.githubusercontent.com/64262215/229373949-0aeaa299-e55f-4b40-9a2e-cd296ce851b4.png)

**Comment by chz091** [comment]
![image](https://user-images.githubusercontent.com/64262215/229373963-d8639c7e-a26a-437e-9697-f1fa7af10184.png)

**Comment by AkashiCoin** [comment]
请使用session_token，直接账号登录暂时不支持
