### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by AlinHuiLI** [AkashiCoin/nonebot-plugin-chatgpt-plus#10]
提示错误信息：请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: ConnectError: All connection attempts failed
![image](https://user-images.githubusercontent.com/130494808/231243539-dfb42754-30b4-4331-8afd-a241bf2ead65.png)
![image](https://user-images.githubusercontent.com/130494808/231243663-10aefdb6-2e3a-41db-a5c4-fee818fa6865.png)
![image](https://user-images.githubusercontent.com/130494808/231243803-da8ba59b-1df6-4afa-a1b9-6bc63d642e02.png)
![image](https://user-images.githubusercontent.com/130494808/231243901-7ecf4aa4-d36b-44fc-a524-146c4a04a6f5.png)
使用api登录了一下可以正常使用，但是插件运行时使用提示错误信息
如果有空和兴趣的话，请帮我解决一下，谢谢

**Comment by AkashiCoin** [comment]
网络问题，可以检查一下网络

**Comment by AkashiCoin** [comment]
但确实是网络问题，请检查使用的代理，是否修改了API什么的
