### ISSUE TITLE
CHATGPT_COMMAND 设置不生效

### ISSUE THREAD

**Issue by QiranYC** [AkashiCoin/nonebot-plugin-chatgpt-plus#25]
![屏幕截图 2023-04-21 005958](https://user-images.githubusercontent.com/97454402/233437573-65948bee-a835-46c4-9d79-56223a95b4fa.png)
在设置后无论是通过 /chat_plus 还是 chat_plus 插件都不响应。
后台日志如下：
04-21 01:02:24 [DEBUG] nonebot | Checking for matchers in priority 1...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers in priority 2...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers in priority 3...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers in priority 4...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers in priority 5...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers in priority 12...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers in priority 98...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers in priority 99...
04-21 01:02:25 [DEBUG] nonebot | Checking for matchers completed

**Comment by AkashiCoin** [comment]
是否@？或者修改是否@机器人的配置，如果设置为True需要@再加关键词才能触发
