### ISSUE TITLE
使用py-plugin插件时CHATGPT_TO_ME配置不生效

### ISSUE THREAD

**Issue by yeyuProject** [AkashiCoin/nonebot-plugin-chatgpt-plus#27]
![image](https://user-images.githubusercontent.com/59468484/233552217-2e8d9c01-d0f6-4571-ade3-57c68a9f1b2d.png)
设置需要@机器人无效

**Comment by yeyuProject** [comment]
补充
![image](https://user-images.githubusercontent.com/59468484/233553289-7c57fdd0-745b-4b8f-97e4-962aa29fdda9.png)

**Comment by AkashiCoin** [comment]
这个回复不是我的插件的回复吧，我的插件是以回复消息的形式进行回答的

**Comment by yeyuProject** [comment]
好的也许是看错了，感谢。
