### ISSUE TITLE
有些回答会引发报错

### ISSUE THREAD

**Issue by Pendome** [AkashiCoin/nonebot-plugin-chatgpt-plus#3]
![image](https://user-images.githubusercontent.com/36023464/229680358-7f54e848-d1fe-437f-a559-b5097096f05c.png)
![image](https://user-images.githubusercontent.com/36023464/229680458-b8d9ba36-a83a-4980-86b5-43c63043af65.png)
版本：v0.8.1
不知道是不是这种返回的代码块的问题

**Comment by AkashiCoin** [comment]
代码块是可以发送的，你这个应该参考go-cq的报错而不是nb的

**Comment by Pendome** [comment]
不好意思，确实是go-cq那里有一行提示
