### ISSUE TITLE
正确填入的access token显示“Token获取失败，请检查配置或API是否可用”

### ISSUE THREAD

**Issue by XTxiaoting14332** [AkashiCoin/nonebot-plugin-chatgpt-plus#30]
填入了最新获取到的access token
但是显示“Token获取失败，请检查配置或API是否可用”
![image](https://user-images.githubusercontent.com/96647974/235275659-9c8120da-57c9-4b69-b834-736490b17177.png)

报错如下
![image](https://user-images.githubusercontent.com/96647974/235275805-d2dce3b7-6447-4eec-bfae-7236ce957c72.png)

**Comment by AkashiCoin** [comment]
使用session token #6

**Comment by XTxiaoting14332** [comment]
> 使用session token #6

填入session token也是一样的
![image](https://user-images.githubusercontent.com/96647974/235342644-206819c9-c512-4da0-8f08-d66720a46213.png)
![image](https://user-images.githubusercontent.com/96647974/235342657-a7806b83-6888-488b-8347-c580d6b817a6.png)
session token是最新获取到的
![image](https://user-images.githubusercontent.com/96647974/235342695-16d6e9cb-a9f0-402e-be69-76177299c217.png)

**Comment by AkashiCoin** [comment]
参考#21

**Comment by XTxiaoting14332** [comment]
解决了 谢谢大佬
