### ISSUE TITLE
access_token和session_token那个优先级更高

### ISSUE THREAD

**Issue by AlinHuiLI** [AkashiCoin/nonebot-plugin-chatgpt-plus#32]
提示依旧为"至少需要配置 session_token 或者 account 和 password"

**Comment by AkashiCoin** [comment]
忘记修改判断了，可以自己改一下在 `chatgpt.py` 47行
```
if self.session_token:
```
为
```
if self.session_token or self.authorization:
```
优先级的话，应该为access_token优先，但是如果配置了session_token也会自动刷新access_token
