### ISSUE TITLE
人格设定的信息似乎在nonebot重启后就会全部丢失？

### ISSUE THREAD

**Issue by Kuju-Asano** [AkashiCoin/nonebot-plugin-chatgpt-plus#36]
如题，翻了下好像没有在本地找到相关保存的文件，不知能否本地保存人格设定😺

**Comment by AkashiCoin** [comment]
会保存，但是是三十分钟自动保存一次，包含所有信息，你可以使用`@bot 刷新token`指令来强制刷新和保存所有信息
这个问题在之后会修复

**Comment by AkashiCoin** [comment]
问题已解决
