### ISSUE TITLE
默认人格的设定是在哪里

### ISSUE THREAD

**Issue by AirKeen76** [AkashiCoin/nonebot-plugin-chatgpt-plus#39]
是setting.json还是config.py呢
![image](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/117345914/7fc537b1-2fa5-4e61-87ce-53529573e98d)
还有格式是截图里这样吗，谢谢大佬

**Comment by AkashiCoin** [comment]
使用以下命令设定人格，并记下名称
![image](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/55268546/01eb4886-4ae9-4974-a2e2-7fb05f644864)
此变量是设置的值为人格的名称
![image](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/55268546/7cb5ca14-fb66-43fe-9b56-1dd7f98665f5)

**Comment by AirKeen76** [comment]
谢谢佬，更新了一下就好了
