### ISSUE TITLE
请求 ChatGPT 服务器时出现问题，请稍后再试 错误信息: ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

### ISSUE THREAD

**Issue by ReiRzior** [AkashiCoin/nonebot-plugin-chatgpt-plus#4]
![124 222 6 11 - 远程桌面连接 2023_4_5 11_30_17 (2)](https://user-images.githubusercontent.com/109207706/229974398-65203daf-4a89-47ab-b14e-7a1595900e30.png)
第一次安装的时候是当一个问题被收到，另一个人中途提问时会报错这个，
第二天的时候就所有消息都是这个恢复了
另外可以问一下人格设置是在文档哪里吗XD

**Comment by ReiRzior** [comment]
我登录后发现chatgpt没有收到请求的问题，在昨天手动清空了一次chatt

**Comment by AkashiCoin** [comment]
这个错误大概是网络不太好，另外人格设定还没写好，先占个位置

**Comment by ReiRzior** [comment]
谢谢，辛苦你啦

**Comment by AkashiCoin** [comment]
人格设定的功能已完成，详细请见更新

**Comment by ReiRzior** [comment]
;)牛牛

**Comment by houliangxue** [comment]
> ![124 222 6 11 - 远程桌面连接 2023_4_5 11_30_17 (2)](https://user-images.githubusercontent.com/109207706/229974398-65203daf-4a89-47ab-b14e-7a1595900e30.png) 第一次安装的时候是当一个问题被收到，另一个人中途提问时会报错这个， 第二天的时候就所有消息都是这个恢复了 另外可以问一下人格设置是在文档哪里吗XD

兄弟，怎么解决的？

**Comment by houliangxue** [comment]
怎么解决这个问题得？我也是这样

**Comment by ReiRzior** [comment]
有点久远记不大清了，好像是更新了就好了，netsh winsock reset之类的也试试吧，再不行刷新token
