### ISSUE TITLE
无法使用了

### ISSUE THREAD

**Issue by 2055135** [AkashiCoin/nonebot-plugin-chatgpt-plus#43]
今天开始出现的，一直在报500错误，网站也打不开
![image](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/119772101/43342a43-aca0-4d2a-af0b-cbab22b6eea4)
![image](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/119772101/3a391a32-a6c8-4340-8c15-7645b02898af)
![image](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/119772101/d94fa978-e18f-4fc2-a6a3-9f2e7a6b3ae0)

**Comment by chaichaisi** [comment]
我也遇到这个问题了，恼(

**Comment by AkashiCoin** [comment]
修了修了
