### ISSUE TITLE
指令使用问题

### ISSUE THREAD

**Issue by YouYouLip** [AkashiCoin/nonebot-plugin-chatgpt-plus#5]
使用刷新会话时需要at机器人才可 配置项里已经设置了CHATGPT_TO_ME=false 但是刷新对话还是要at 包括查看人格之类的，插件前天安的，应该是昨天更新的问题吗？ 今天下午更新就这样了，早上还可以不用at的说 突然不习惯了

**Comment by AkashiCoin** [comment]
CHATGPT_TO_ME设置的是机器人响应请求是否需要@，配置指令之类的都需要@

**Comment by YouYouLip** [comment]
> CHATGPT_TO_ME设置的是机器人响应请求是否需要@，配置指令之类的都需要@

了解了 刷新对话配置指令在群里需要@ 是我忽略这个问题了 私聊并不需要
