### ISSUE TITLE
token错误

### ISSUE THREAD

**Issue by zhoudj111** [AkashiCoin/nonebot-plugin-chatgpt-plus#50]
现在chatgpt的哪个token好像每次都会变化，这个配置的token好像不行了

**Comment by 2055135** [comment]
额

**Comment by 2055135** [comment]
好像是网站反代成新版了
![image](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/119772101/655971df-4efd-4663-88ab-2f2c03e03acf)
