### ISSUE TITLE
获取到的消息不完整

### ISSUE THREAD

**Issue by watershed117** [AkashiCoin/nonebot-plugin-chatgpt-plus#52]
![QQ图片20231116002100](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/assets/118862661/bc47b7eb-c46d-406e-ad8a-cf62ba1b31ed)
无法获取到完整消息，反向代理出问题了吗

**Comment by watershed117** [comment]
[chat_web.zip](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/files/13367052/chat_web.zip)
这是我的插件源码

**Comment by AkashiCoin** [comment]
最新可以使用了
