### ISSUE TITLE
部署好后报错，无法使用

### ISSUE THREAD

**Issue by nikissXI** [AkashiCoin/nonebot-plugin-chatgpt-plus#6]
![{%B I~Q_3EW5F D5OXP(15A](https://user-images.githubusercontent.com/31379266/230713118-6ce30390-6815-4d89-914a-0059dfc0b417.png)
使用accessToken登录

**Comment by nikissXI** [comment]
我改了下代码把响应输出是这个
![image](https://user-images.githubusercontent.com/31379266/230713911-824b02c9-acc4-4b8d-ab78-d68fb93796aa.png)

**Comment by AkashiCoin** [comment]
使用session_token或者账号密码，详细看readme

**Comment by nikissXI** [comment]
> 使用session_token或者账号密码，详细看readme

试过了，都是这个报错，难道就我一个用不了？

**Comment by nikissXI** [comment]
前面说错了，不是accessToken，就是用的session token登录的

**Comment by nikissXI** [comment]
靠，换0.8.2没事了，0.8.3有问题
