### ISSUE TITLE
0.8.2使用查看会话报错了

### ISSUE THREAD

**Issue by nikissXI** [AkashiCoin/nonebot-plugin-chatgpt-plus#7]
因为0.8.3直接无法使用，所以我现在用的是0.8.2
![image](https://user-images.githubusercontent.com/31379266/230724573-deb2f1d5-0529-4761-9681-91b293615098.png)

**Comment by AkashiCoin** [comment]
需要拥有会话才能查到，比如使用过保存会话+名称，才能查到会话，否则无法查询，若是需要查看会话id什么的，使用导出会话的功能

**Comment by AkashiCoin** [comment]
还有你的0.8.3无法使用的问题，在修改环境变量后是否删除掉了settings.json文件，未删除的话会从这个文件中读取相关token信息，就会出现即使修改了配置也无法使用的情况

**Comment by nikissXI** [comment]
0.8.3我是新安装的

**Comment by AkashiCoin** [comment]
请使用最新版，此issue关闭
