### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by Pendome** [AkashiCoin/nonebot-plugin-chatgpt-plus#8]
![image](https://user-images.githubusercontent.com/36023464/231036353-f66f360d-a8bc-4b7c-aea7-c26c98fedd30.png)
今天使用突然就报了这个错

**Comment by cj1357** [comment]
我也是，提示：
请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: ValueError: Tag "<html>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
![image](https://user-images.githubusercontent.com/40661342/231044623-755728fc-55a9-438d-9580-3f670717761a.png)

**Comment by cj1357** [comment]
我去openai官网看了一下，说是我的被禁止访问了，这是被封号了吗？好像封号不是这个提示吧
![image](https://user-images.githubusercontent.com/40661342/231045999-581cf920-770c-4f20-bc78-8e69de22203e.png)

**Comment by Pendome** [comment]
好像官网加了个校验机器人的东西，需要点一下才给你通过的东西，在使用同一个sessionToken的时候官网也不能用了，需要要刷新一下token才会正常。

**Comment by AkashiCoin** [comment]
api问题，已修复

**Comment by JustinHuangber** [comment]
遇到了同样的问题，版本为0.8.4
